# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night-eighties # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : harry’s blog
description: >  
              harry's technology blog 
# this means to ignore newlines until "Language & timezone"


## => Language and Timezone
##############################
lang: en
timezone: Asia/Shanghai


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  avatar    : /assets/apple-touch-icon.png
  name      : harry
  email     : harry_c2016@163.com
  github    : HaoXiansen
#  douban    : chenfh5


## => GitHub Repository (if the site is hosted by GitHub)
##############################https://github.com/HaoXianSen
repository: HaoXianSen/HaoXianSen.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: ture # false (default), true

## Mermaid
mermaid: ture# false (default), true

## Chart
chart: ture # false (default), true


## => Paginate
##############################
paginate: 15
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: bootcdn # bootcdn (default), unpkg


## => Sharing
##############################
# sharing:
#   provider: # false (default), "addtoany", "addthis", "custom"

#   ## AddThis
#   addthis:
#     id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
# comments:
#   provider: gitalk
#   gitalk:
#     clientID    : "94156de881bfeb261eac"
#     clientSecret: "2675ee08f2fc782693cf0a22c1feb3b2a3cc877b"
#     repository  : "https://github.com/HaoXianSen"
#     owner       : "HaoXianSen"
    #admin: # Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
      #- "your-github-id"
      #- "the-other-admin-github-id"
comments:
  provider: valine
  valine:
    app_id  : "Woz7nxEuYtaxBK6LCyrFCy4V-gzGzoHsz"
    app_key : "lov4hbnuItCqFbENTixANHK4"

## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id    : "Woz7nxEuYtaxBK6LCyrFCy4V-gzGzoHsz"
    app_key   : "lov4hbnuItCqFbENTixANHK4"
    app_class : "clicks"


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  #google:
   # custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
# analytics:
#   provider: google # false (default), "google", "custom"

#   ## Google Analytics
#   google:
#     tracking_id : UA-139325997-1
#     anonymize_ip: false


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: false
      pageview: true

# sidebar:
#   nav: docs-en

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
