#!/usr/bin/env bash

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$DIR" || exit 1
git status 
git add .
git commit -m "更新文章"
git fetch
git pull origin master
git status
git push origin master

exit 0

